version: '3.8'

services:
  db:
    image: postgres:15
    container_name: pizzaria-db
    restart: always
    environment:
      POSTGRES_USER: lucas
      POSTGRES_PASSWORD: massa123
      POSTGRES_DB: pizzaria
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U lucas"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - pizzaria-net

volumes:
  pgdata:

networks:
  pizzaria-net:
    driver: bridge
